spring:
  datasource:
    url: jdbc:mysql://localhost:3306/YourDBname
    username: YourID
    password: YourPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      show-sql : true
