spring:
  mail:
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    sender-email: ${SENDER_EMAIL}
  #.env 파일 인식 설정 추가
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

cookie:
  domain: localhost

#spring:
  servlet:
    multipart:
      max-file-size: 16MB  # Set desired maximum file size
      max-request-size: 16MB  # Set desired maximum request size

server:
  tomcat:
    max-swallow-size: 16MB  # This sets the maximum size, Tomcat will swallow
